import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

function Index() {
  return (
    <>
      <Head>
        <title>GameXperience</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <h1>GameXperience</h1>
        <h4>"Tu biblioteca de videojuegos"</h4>
        <input type="text" name="tipo_de_dato"/>
        <button>Buscar</button>
        <Link href="/games">
        <button>Ir a mi archivo JS</button>
      </Link>
      </section>
    </>
  )
}

export default Index